name: Generate Snake Animation

on:
  schedule:               # Run automatically every day
    - cron: "0 0 * * *"
  workflow_dispatch:      # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: vaghaniharshh
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: actions@github.com
          message: "🐍 Generated Snake Animation"
          add: "dist/github-contribution-grid-snake.svg"
